source 'http://ruby.taobao.org'

gem 'rails', '3.2.8'
gem 'mongoid', '~> 3.0.0'
gem 'bson_ext'
gem 'slim-rails', '~> 1.0.3'
gem 'simple_form', '~> 2.0.4'
gem 'json'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'twitter-bootstrap-rails', '2.1.6'
  gem 'sass-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'less-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

#gem 'jquery-rails'
gem 'cloudfoundry-jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

group :development do
  gem 'thin'
end

# Use unicorn as the app server
group :production do
  gem 'unicorn'
end

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
